version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=ncryptd
      - DB_USERNAME=root
      - DB_PASSWORD=root

  db:
    image: mysql:5.7
    ports:
      - "33061:3306"
    environment:
      - MYSQL_DATABASE=ncryptd
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql

  composer:
    image: composer:2
    volumes:
      - .:/app
    command: install

volumes:
  db_data:
